version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    image: confluentinc/cp-kafka:latest
    command: bash -c "seq 1000 | kafka-console-producer --broker-list kafka:9092 --topic test && sleep 3600"
    depends_on:
      - kafka

  consumer:
    image: confluentinc/cp-kafka:latest
    command: kafka-console-consumer --bootstrap-server kafka:9092 --topic test --from-beginning
    depends_on:
      - kafka
